### ISSUE TITLE
Forwarding a picture on whatsapp turns it into a document

### ISSUE THREAD

**Issue by hseg** [d99kris/nchat#280]
**Description**: When forwarding an image in a Whatsapp account, it appears as a document.

**How to reproduce it**: Send a JPG image over whatsapp. Select it and press `<alt-r>` to forward it to (even the same!) chat. Notice when it arrives that what was an image now appears as a document (indeed, its name is now changed from `hash.jpg` to `hash-hash.jpg` for some hashes `hash`)

**Environment**:
- Version: nchat 5.1.29
- OS / distro: Linux 6.10.4-arch2-1

**Comment by d99kris** [comment]
Hi @hseg - thanks for reporting a bug! I can reproducing the issue here as well. Will look into this.

**Comment by d99kris** [comment]
Hi again - the issue should be fixed with above commit. Please let me know if it's not.

**Comment by hseg** [comment]
It didn't fix it -- just tested it with a build off ca01274, and I still can reproduce: I forwarded a JPG back to myself, and got it as a document

EDIT: For some reason, rebuilding nchat on that version does fix the bug. If this strikes again, I'll reopen the bug, but for now things look good.
One thing that may have confused me is that I checked the version using my package manager -- it may be useful to have `nchat --version` report the commit it was built on for sanity-checking

**Comment by d99kris** [comment]
> it may be useful to have `nchat --version` report the commit it was built on for sanity-checking

Thanks for the suggestion, I'll see if I can add this.
